-- All ISO 3166-1 Countries
INSERT INTO countries (code, name, phone_code, currency_code, sequence) VALUES
('AF', 'Afghanistan', '+93', 'AFN', 100),
('AL', 'Albania', '+355', 'ALL', 100),
('DZ', 'Algeria', '+213', 'DZD', 100),
('AS', 'American Samoa', '+1-684', 'USD', 100),
('AD', 'Andorra', '+376', 'EUR', 100),
('AO', 'Angola', '+244', 'AOA', 100),
('AI', 'Anguilla', '+1-264', 'XCD', 100),
('AQ', 'Antarctica', '+672', 'AAD', 100),
('AG', 'Antigua and Barbuda', '+1-268', 'XCD', 100),
('AR', 'Argentina', '+54', 'ARS', 100),
('AM', 'Armenia', '+374', 'AMD', 100),
('AW', 'Aruba', '+297', 'AWG', 100),
('AT', 'Austria', '+43', 'EUR', 100),
('AZ', 'Azerbaijan', '+994', 'AZN', 100),
('BS', 'Bahamas', '+1-242', 'BSD', 100),
('BH', 'Bahrain', '+973', 'BHD', 100),
('BD', 'Bangladesh', '+880', 'BDT', 100),
('BB', 'Barbados', '+1-246', 'BBD', 100),
('BY', 'Belarus', '+375', 'BYN', 100),
('BZ', 'Belize', '+501', 'BZD', 100),
('BJ', 'Benin', '+229', 'XOF', 100),
('BM', 'Bermuda', '+1-441', 'BMD', 100),
('BT', 'Bhutan', '+975', 'BTN', 100),
('BO', 'Bolivia', '+591', 'BOB', 100),
('BA', 'Bosnia and Herzegovina', '+387', 'BAM', 100),
('BW', 'Botswana', '+267', 'BWP', 100),
('BV', 'Bouvet Island', '+47', 'NOK', 100),
('IO', 'British Indian Ocean Territory', '+246', 'USD', 100),
('BN', 'Brunei', '+673', 'BND', 100),
('BG', 'Bulgaria', '+359', 'BGN', 100),
('BF', 'Burkina Faso', '+226', 'XOF', 100),
('BI', 'Burundi', '+257', 'BIF', 100),
('KH', 'Cambodia', '+855', 'KHR', 100),
('CM', 'Cameroon', '+237', 'XAF', 100),
('CV', 'Cape Verde', '+238', 'CVE', 100),
('KY', 'Cayman Islands', '+1-345', 'KYD', 100),
('CF', 'Central African Republic', '+236', 'XAF', 100),
('TD', 'Chad', '+235', 'XAF', 100),
('CL', 'Chile', '+56', 'CLP', 100),
('CX', 'Christmas Island', '+61', 'AUD', 100),
('CC', 'Cocos Islands', '+61', 'AUD', 100),
('CO', 'Colombia', '+57', 'COP', 100),
('KM', 'Comoros', '+269', 'KMF', 100),
('CG', 'Congo', '+242', 'XAF', 100),
('CD', 'Congo, Democratic Republic', '+243', 'CDF', 100),
('CK', 'Cook Islands', '+682', 'NZD', 100),
('CR', 'Costa Rica', '+506', 'CRC', 100),
('CI', 'Ivory Coast', '+225', 'XOF', 100),
('HR', 'Croatia', '+385', 'EUR', 100),
('CU', 'Cuba', '+53', 'CUP', 100),
('CW', 'Curacao', '+599', 'ANG', 100),
('CY', 'Cyprus', '+357', 'EUR', 100),
('CZ', 'Czech Republic', '+420', 'CZK', 100),
('DK', 'Denmark', '+45', 'DKK', 100),
('DJ', 'Djibouti', '+253', 'DJF', 100),
('DM', 'Dominica', '+1-767', 'XCD', 100),
('DO', 'Dominican Republic', '+1-809', 'DOP', 100),
('EC', 'Ecuador', '+593', 'USD', 100),
('EG', 'Egypt', '+20', 'EGP', 100),
('SV', 'El Salvador', '+503', 'USD', 100),
('GQ', 'Equatorial Guinea', '+240', 'XAF', 100),
('ER', 'Eritrea', '+291', 'ERN', 100),
('EE', 'Estonia', '+372', 'EUR', 100),
('SZ', 'Eswatini', '+268', 'SZL', 100),
('ET', 'Ethiopia', '+251', 'ETB', 100),
('FK', 'Falkland Islands', '+500', 'FKP', 100),
('FO', 'Faroe Islands', '+298', 'DKK', 100),
('FJ', 'Fiji', '+679', 'FJD', 100),
('FI', 'Finland', '+358', 'EUR', 100),
('GF', 'French Guiana', '+594', 'EUR', 100),
('PF', 'French Polynesia', '+689', 'XPF', 100),
('GA', 'Gabon', '+241', 'XAF', 100),
('GM', 'Gambia', '+220', 'GMD', 100),
('GE', 'Georgia', '+995', 'GEL', 100),
('GH', 'Ghana', '+233', 'GHS', 100),
('GI', 'Gibraltar', '+350', 'GIP', 100),
('GR', 'Greece', '+30', 'EUR', 100),
('GL', 'Greenland', '+299', 'DKK', 100),
('GD', 'Grenada', '+1-473', 'XCD', 100),
('GP', 'Guadeloupe', '+590', 'EUR', 100),
('GU', 'Guam', '+1-671', 'USD', 100),
('GT', 'Guatemala', '+502', 'GTQ', 100),
('GG', 'Guernsey', '+44-1481', 'GBP', 100),
('GN', 'Guinea', '+224', 'GNF', 100),
('GW', 'Guinea-Bissau', '+245', 'XOF', 100),
('GY', 'Guyana', '+592', 'GYD', 100),
('HT', 'Haiti', '+509', 'HTG', 100),
('HN', 'Honduras', '+504', 'HNL', 100),
('HK', 'Hong Kong', '+852', 'HKD', 100),
('HU', 'Hungary', '+36', 'HUF', 100),
('IS', 'Iceland', '+354', 'ISK', 100),
('ID', 'Indonesia', '+62', 'IDR', 100),
('IR', 'Iran', '+98', 'IRR', 100),
('IQ', 'Iraq', '+964', 'IQD', 100),
('IE', 'Ireland', '+353', 'EUR', 100),
('IM', 'Isle of Man', '+44-1624', 'GBP', 100),
('IL', 'Israel', '+972', 'ILS', 100),
('JM', 'Jamaica', '+1-876', 'JMD', 100),
('JE', 'Jersey', '+44-1534', 'GBP', 100),
('JO', 'Jordan', '+962', 'JOD', 100),
('KZ', 'Kazakhstan', '+7', 'KZT', 100),
('KE', 'Kenya', '+254', 'KES', 100),
('KI', 'Kiribati', '+686', 'AUD', 100),
('KP', 'North Korea', '+850', 'KPW', 100),
('KR', 'South Korea', '+82', 'KRW', 100),
('KW', 'Kuwait', '+965', 'KWD', 100),
('KG', 'Kyrgyzstan', '+996', 'KGS', 100),
('LA', 'Laos', '+856', 'LAK', 100),
('LV', 'Latvia', '+371', 'EUR', 100),
('LB', 'Lebanon', '+961', 'LBP', 100),
('LS', 'Lesotho', '+266', 'LSL', 100),
('LR', 'Liberia', '+231', 'LRD', 100),
('LY', 'Libya', '+218', 'LYD', 100),
('LI', 'Liechtenstein', '+423', 'CHF', 100),
('LT', 'Lithuania', '+370', 'EUR', 100),
('LU', 'Luxembourg', '+352', 'EUR', 100),
('MO', 'Macao', '+853', 'MOP', 100),
('MG', 'Madagascar', '+261', 'MGA', 100),
('MW', 'Malawi', '+265', 'MWK', 100),
('MY', 'Malaysia', '+60', 'MYR', 100),
('MV', 'Maldives', '+960', 'MVR', 100),
('ML', 'Mali', '+223', 'XOF', 100),
('MT', 'Malta', '+356', 'EUR', 100),
('MH', 'Marshall Islands', '+692', 'USD', 100),
('MQ', 'Martinique', '+596', 'EUR', 100),
('MR', 'Mauritania', '+222', 'MRU', 100),
('MU', 'Mauritius', '+230', 'MUR', 100),
('YT', 'Mayotte', '+262', 'EUR', 100),
('FM', 'Micronesia', '+691', 'USD', 100),
('MD', 'Moldova', '+373', 'MDL', 100),
('MC', 'Monaco', '+377', 'EUR', 100),
('MN', 'Mongolia', '+976', 'MNT', 100),
('ME', 'Montenegro', '+382', 'EUR', 100),
('MS', 'Montserrat', '+1-664', 'XCD', 100),
('MA', 'Morocco', '+212', 'MAD', 100),
('MZ', 'Mozambique', '+258', 'MZN', 100),
('MM', 'Myanmar', '+95', 'MMK', 100),
('NA', 'Namibia', '+264', 'NAD', 100),
('NR', 'Nauru', '+674', 'AUD', 100),
('NP', 'Nepal', '+977', 'NPR', 100),
('NC', 'New Caledonia', '+687', 'XPF', 100),
('NZ', 'New Zealand', '+64', 'NZD', 100),
('NI', 'Nicaragua', '+505', 'NIO', 100),
('NE', 'Niger', '+227', 'XOF', 100),
('NG', 'Nigeria', '+234', 'NGN', 100),
('NU', 'Niue', '+683', 'NZD', 100),
('NF', 'Norfolk Island', '+672', 'AUD', 100),
('MK', 'North Macedonia', '+389', 'MKD', 100),
('MP', 'Northern Mariana Islands', '+1-670', 'USD', 100),
('NO', 'Norway', '+47', 'NOK', 100),
('OM', 'Oman', '+968', 'OMR', 100),
('PK', 'Pakistan', '+92', 'PKR', 100),
('PW', 'Palau', '+680', 'USD', 100),
('PS', 'Palestine', '+970', 'ILS', 100),
('PA', 'Panama', '+507', 'PAB', 100),
('PG', 'Papua New Guinea', '+675', 'PGK', 100),
('PY', 'Paraguay', '+595', 'PYG', 100),
('PE', 'Peru', '+51', 'PEN', 100),
('PH', 'Philippines', '+63', 'PHP', 100),
('PN', 'Pitcairn', '+64', 'NZD', 100),
('PL', 'Poland', '+48', 'PLN', 100),
('PT', 'Portugal', '+351', 'EUR', 100),
('PR', 'Puerto Rico', '+1-787', 'USD', 100),
('QA', 'Qatar', '+974', 'QAR', 100),
('RE', 'Reunion', '+262', 'EUR', 100),
('RO', 'Romania', '+40', 'RON', 100),
('RU', 'Russia', '+7', 'RUB', 100),
('RW', 'Rwanda', '+250', 'RWF', 100),
('BL', 'Saint Barthelemy', '+590', 'EUR', 100),
('SH', 'Saint Helena', '+290', 'SHP', 100),
('KN', 'Saint Kitts and Nevis', '+1-869', 'XCD', 100),
('LC', 'Saint Lucia', '+1-758', 'XCD', 100),
('MF', 'Saint Martin', '+590', 'EUR', 100),
('PM', 'Saint Pierre and Miquelon', '+508', 'EUR', 100),
('VC', 'Saint Vincent and the Grenadines', '+1-784', 'XCD', 100),
('WS', 'Samoa', '+685', 'WST', 100),
('SM', 'San Marino', '+378', 'EUR', 100),
('ST', 'Sao Tome and Principe', '+239', 'STN', 100),
('SA', 'Saudi Arabia', '+966', 'SAR', 100),
('SN', 'Senegal', '+221', 'XOF', 100),
('RS', 'Serbia', '+381', 'RSD', 100),
('SC', 'Seychelles', '+248', 'SCR', 100),
('SL', 'Sierra Leone', '+232', 'SLL', 100),
('SG', 'Singapore', '+65', 'SGD', 100),
('SX', 'Sint Maarten', '+1-721', 'ANG', 100),
('SK', 'Slovakia', '+421', 'EUR', 100),
('SI', 'Slovenia', '+386', 'EUR', 100),
('SB', 'Solomon Islands', '+677', 'SBD', 100),
('SO', 'Somalia', '+252', 'SOS', 100),
('ZA', 'South Africa', '+27', 'ZAR', 100),
('GS', 'South Georgia', '+500', 'GBP', 100),
('SS', 'South Sudan', '+211', 'SSP', 100),
('LK', 'Sri Lanka', '+94', 'LKR', 100),
('SD', 'Sudan', '+249', 'SDG', 100),
('SR', 'Suriname', '+597', 'SRD', 100),
('SJ', 'Svalbard and Jan Mayen', '+47', 'NOK', 100),
('SE', 'Sweden', '+46', 'SEK', 100),
('CH', 'Switzerland', '+41', 'CHF', 100),
('SY', 'Syria', '+963', 'SYP', 100),
('TW', 'Taiwan', '+886', 'TWD', 100),
('TJ', 'Tajikistan', '+992', 'TJS', 100),
('TZ', 'Tanzania', '+255', 'TZS', 100),
('TH', 'Thailand', '+66', 'THB', 100),
('TL', 'Timor-Leste', '+670', 'USD', 100),
('TG', 'Togo', '+228', 'XOF', 100),
('TK', 'Tokelau', '+690', 'NZD', 100),
('TO', 'Tonga', '+676', 'TOP', 100),
('TT', 'Trinidad and Tobago', '+1-868', 'TTD', 100),
('TN', 'Tunisia', '+216', 'TND', 100),
('TR', 'Turkey', '+90', 'TRY', 100),
('TM', 'Turkmenistan', '+993', 'TMT', 100),
('TC', 'Turks and Caicos Islands', '+1-649', 'USD', 100),
('TV', 'Tuvalu', '+688', 'AUD', 100),
('UG', 'Uganda', '+256', 'UGX', 100),
('UA', 'Ukraine', '+380', 'UAH', 100),
('AE', 'United Arab Emirates', '+971', 'AED', 100),
('UM', 'United States Minor Outlying Islands', '+1', 'USD', 100),
('UY', 'Uruguay', '+598', 'UYU', 100),
('UZ', 'Uzbekistan', '+998', 'UZS', 100),
('VU', 'Vanuatu', '+678', 'VUV', 100),
('VA', 'Vatican City', '+379', 'EUR', 100),
('VE', 'Venezuela', '+58', 'VES', 100),
('VN', 'Vietnam', '+84', 'VND', 100),
('VG', 'British Virgin Islands', '+1-284', 'USD', 100),
('VI', 'U.S. Virgin Islands', '+1-340', 'USD', 100),
('WF', 'Wallis and Futuna', '+681', 'XPF', 100),
('EH', 'Western Sahara', '+212', 'MAD', 100),
('YE', 'Yemen', '+967', 'YER', 100),
('ZM', 'Zambia', '+260', 'ZMW', 100),
('ZW', 'Zimbabwe', '+263', 'ZWL', 100)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, phone_code = EXCLUDED.phone_code, currency_code = EXCLUDED.currency_code;

-- Add more Indian states
INSERT INTO states (country_id, code, name)
SELECT c.id, s.code, s.name FROM countries c, (VALUES
    ('AN', 'Andaman and Nicobar Islands'),
    ('AP', 'Andhra Pradesh'),
    ('AR', 'Arunachal Pradesh'),
    ('AS', 'Assam'),
    ('BR', 'Bihar'),
    ('CH', 'Chandigarh'),
    ('CT', 'Chhattisgarh'),
    ('DN', 'Dadra and Nagar Haveli'),
    ('DD', 'Daman and Diu'),
    ('DL', 'Delhi'),
    ('GA', 'Goa'),
    ('GJ', 'Gujarat'),
    ('HR', 'Haryana'),
    ('HP', 'Himachal Pradesh'),
    ('JK', 'Jammu and Kashmir'),
    ('JH', 'Jharkhand'),
    ('KA', 'Karnataka'),
    ('KL', 'Kerala'),
    ('LA', 'Ladakh'),
    ('LD', 'Lakshadweep'),
    ('MP', 'Madhya Pradesh'),
    ('MH', 'Maharashtra'),
    ('MN', 'Manipur'),
    ('ML', 'Meghalaya'),
    ('MZ', 'Mizoram'),
    ('NL', 'Nagaland'),
    ('OR', 'Odisha'),
    ('PY', 'Puducherry'),
    ('PB', 'Punjab'),
    ('RJ', 'Rajasthan'),
    ('SK', 'Sikkim'),
    ('TN', 'Tamil Nadu'),
    ('TG', 'Telangana'),
    ('TR', 'Tripura'),
    ('UP', 'Uttar Pradesh'),
    ('UK', 'Uttarakhand'),
    ('WB', 'West Bengal')
) AS s(code, name) WHERE c.code = 'IN'
ON CONFLICT (country_id, code) DO NOTHING;

-- Add UK regions
INSERT INTO states (country_id, code, name)
SELECT c.id, s.code, s.name FROM countries c, (VALUES
    ('ENG', 'England'),
    ('SCT', 'Scotland'),
    ('WLS', 'Wales'),
    ('NIR', 'Northern Ireland')
) AS s(code, name) WHERE c.code = 'GB'
ON CONFLICT (country_id, code) DO NOTHING;

-- Add German states
INSERT INTO states (country_id, code, name)
SELECT c.id, s.code, s.name FROM countries c, (VALUES
    ('BW', 'Baden-Wurttemberg'),
    ('BY', 'Bavaria'),
    ('BE', 'Berlin'),
    ('BB', 'Brandenburg'),
    ('HB', 'Bremen'),
    ('HH', 'Hamburg'),
    ('HE', 'Hesse'),
    ('MV', 'Mecklenburg-Vorpommern'),
    ('NI', 'Lower Saxony'),
    ('NW', 'North Rhine-Westphalia'),
    ('RP', 'Rhineland-Palatinate'),
    ('SL', 'Saarland'),
    ('SN', 'Saxony'),
    ('ST', 'Saxony-Anhalt'),
    ('SH', 'Schleswig-Holstein'),
    ('TH', 'Thuringia')
) AS s(code, name) WHERE c.code = 'DE'
ON CONFLICT (country_id, code) DO NOTHING;

-- Add Brazilian states
INSERT INTO states (country_id, code, name)
SELECT c.id, s.code, s.name FROM countries c, (VALUES
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapa'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceara'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espirito Santo'),
    ('GO', 'Goias'),
    ('MA', 'Maranhao'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Para'),
    ('PB', 'Paraiba'),
    ('PR', 'Parana'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piaui'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondonia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'Sao Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins')
) AS s(code, name) WHERE c.code = 'BR'
ON CONFLICT (country_id, code) DO NOTHING;

-- Add Chinese provinces
INSERT INTO states (country_id, code, name)
SELECT c.id, s.code, s.name FROM countries c, (VALUES
    ('AH', 'Anhui'),
    ('BJ', 'Beijing'),
    ('CQ', 'Chongqing'),
    ('FJ', 'Fujian'),
    ('GS', 'Gansu'),
    ('GD', 'Guangdong'),
    ('GX', 'Guangxi'),
    ('GZ', 'Guizhou'),
    ('HI', 'Hainan'),
    ('HE', 'Hebei'),
    ('HL', 'Heilongjiang'),
    ('HA', 'Henan'),
    ('HK', 'Hong Kong'),
    ('HB', 'Hubei'),
    ('HN', 'Hunan'),
    ('JS', 'Jiangsu'),
    ('JX', 'Jiangxi'),
    ('JL', 'Jilin'),
    ('LN', 'Liaoning'),
    ('MO', 'Macao'),
    ('NM', 'Inner Mongolia'),
    ('NX', 'Ningxia'),
    ('QH', 'Qinghai'),
    ('SN', 'Shaanxi'),
    ('SD', 'Shandong'),
    ('SH', 'Shanghai'),
    ('SX', 'Shanxi'),
    ('SC', 'Sichuan'),
    ('TJ', 'Tianjin'),
    ('XJ', 'Xinjiang'),
    ('XZ', 'Tibet'),
    ('YN', 'Yunnan'),
    ('ZJ', 'Zhejiang')
) AS s(code, name) WHERE c.code = 'CN'
ON CONFLICT (country_id, code) DO NOTHING;

-- Add Japanese prefectures
INSERT INTO states (country_id, code, name)
SELECT c.id, s.code, s.name FROM countries c, (VALUES
    ('01', 'Hokkaido'),
    ('02', 'Aomori'),
    ('03', 'Iwate'),
    ('04', 'Miyagi'),
    ('05', 'Akita'),
    ('06', 'Yamagata'),
    ('07', 'Fukushima'),
    ('08', 'Ibaraki'),
    ('09', 'Tochigi'),
    ('10', 'Gunma'),
    ('11', 'Saitama'),
    ('12', 'Chiba'),
    ('13', 'Tokyo'),
    ('14', 'Kanagawa'),
    ('15', 'Niigata'),
    ('16', 'Toyama'),
    ('17', 'Ishikawa'),
    ('18', 'Fukui'),
    ('19', 'Yamanashi'),
    ('20', 'Nagano'),
    ('21', 'Gifu'),
    ('22', 'Shizuoka'),
    ('23', 'Aichi'),
    ('24', 'Mie'),
    ('25', 'Shiga'),
    ('26', 'Kyoto'),
    ('27', 'Osaka'),
    ('28', 'Hyogo'),
    ('29', 'Nara'),
    ('30', 'Wakayama'),
    ('31', 'Tottori'),
    ('32', 'Shimane'),
    ('33', 'Okayama'),
    ('34', 'Hiroshima'),
    ('35', 'Yamaguchi'),
    ('36', 'Tokushima'),
    ('37', 'Kagawa'),
    ('38', 'Ehime'),
    ('39', 'Kochi'),
    ('40', 'Fukuoka'),
    ('41', 'Saga'),
    ('42', 'Nagasaki'),
    ('43', 'Kumamoto'),
    ('44', 'Oita'),
    ('45', 'Miyazaki'),
    ('46', 'Kagoshima'),
    ('47', 'Okinawa')
) AS s(code, name) WHERE c.code = 'JP'
ON CONFLICT (country_id, code) DO NOTHING;

-- Add French regions
INSERT INTO states (country_id, code, name)
SELECT c.id, s.code, s.name FROM countries c, (VALUES
    ('ARA', 'Auvergne-Rhone-Alpes'),
    ('BFC', 'Bourgogne-Franche-Comte'),
    ('BRE', 'Brittany'),
    ('CVL', 'Centre-Val de Loire'),
    ('COR', 'Corsica'),
    ('GES', 'Grand Est'),
    ('HDF', 'Hauts-de-France'),
    ('IDF', 'Ile-de-France'),
    ('NOR', 'Normandy'),
    ('NAQ', 'Nouvelle-Aquitaine'),
    ('OCC', 'Occitanie'),
    ('PDL', 'Pays de la Loire'),
    ('PAC', 'Provence-Alpes-Cote d Azur')
) AS s(code, name) WHERE c.code = 'FR'
ON CONFLICT (country_id, code) DO NOTHING;

-- Add Spanish autonomous communities
INSERT INTO states (country_id, code, name)
SELECT c.id, s.code, s.name FROM countries c, (VALUES
    ('AN', 'Andalusia'),
    ('AR', 'Aragon'),
    ('AS', 'Asturias'),
    ('IB', 'Balearic Islands'),
    ('PV', 'Basque Country'),
    ('CN', 'Canary Islands'),
    ('CB', 'Cantabria'),
    ('CL', 'Castile and Leon'),
    ('CM', 'Castilla-La Mancha'),
    ('CT', 'Catalonia'),
    ('EX', 'Extremadura'),
    ('GA', 'Galicia'),
    ('MD', 'Madrid'),
    ('MC', 'Murcia'),
    ('NC', 'Navarre'),
    ('RI', 'La Rioja'),
    ('VC', 'Valencia')
) AS s(code, name) WHERE c.code = 'ES'
ON CONFLICT (country_id, code) DO NOTHING;

-- Add Italian regions
INSERT INTO states (country_id, code, name)
SELECT c.id, s.code, s.name FROM countries c, (VALUES
    ('ABR', 'Abruzzo'),
    ('BAS', 'Basilicata'),
    ('CAL', 'Calabria'),
    ('CAM', 'Campania'),
    ('EMR', 'Emilia-Romagna'),
    ('FVG', 'Friuli Venezia Giulia'),
    ('LAZ', 'Lazio'),
    ('LIG', 'Liguria'),
    ('LOM', 'Lombardy'),
    ('MAR', 'Marche'),
    ('MOL', 'Molise'),
    ('PMN', 'Piedmont'),
    ('PUG', 'Apulia'),
    ('SAR', 'Sardinia'),
    ('SIC', 'Sicily'),
    ('TOS', 'Tuscany'),
    ('TAA', 'Trentino-Alto Adige'),
    ('UMB', 'Umbria'),
    ('VDA', 'Aosta Valley'),
    ('VEN', 'Veneto')
) AS s(code, name) WHERE c.code = 'IT'
ON CONFLICT (country_id, code) DO NOTHING;
