/**
 * Build-time Tailwind config for Vortex.
 *
 * Replaces the browser-runtime Tailwind "Play CDN" (`vendor/tailwind.js`)
 * with a static, purged stylesheet generated by the standalone Tailwind CLI
 * — no npm, no node_modules, no client-side compilation. Run via
 * `tools/css/build.sh`, which emits `crates/vortex-cli/static/tailwind.css`.
 *
 * DaisyUI is NOT a plugin here: it ships as its own prebuilt
 * `vendor/daisyui.min.css` (component + theme layer). This build only
 * produces Tailwind's base reset + the utility classes actually used across
 * the Rust handlers, HTML templates, and static JS.
 */
module.exports = {
  content: [
    "/home/vortex/vortex-core/crates/**/*.rs",
    "/home/vortex/vortex-core/crates/**/*.html",
    // Static JS that toggles classes at runtime (top level only — never the
    // vendored libraries, whose minified blobs would inject junk utilities).
    "/home/vortex/vortex-core/crates/vortex-cli/static/*.js",
  ],
  // Brand palette carried over verbatim from the former inline
  // `tailwind.config` blocks so any `*-remicle-*` utility still resolves.
  theme: {
    extend: {
      colors: {
        remicle: {
          green: "#8BC53F",
          "green-dark": "#6BA32E",
          gray: "#6D6E71",
          "gray-light": "#9D9FA2",
        },
      },
    },
  },
  // Classes assembled dynamically in Rust (`format!("...-{}", x)`) that the
  // content scanner cannot see as whole tokens. DaisyUI component classes
  // (btn-*, badge-*, alert-*, …) do NOT need listing — they live in the
  // prebuilt daisyui.min.css. Keep this list tight; add only proven gaps.
  safelist: [
    { pattern: /^(text|bg|border|from|to|via)-remicle-(green|green-dark|gray|gray-light)$/ },
  ],
};
